name: RasmusHulgaard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfd7d1'
    - '#101010'
    - '#de0000'
    - '#ff576b'
    - '#009cdd'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.4602866368368268
  rhythmicContrast: 0.7584343464113772
purpose: []
